apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloapp
  name: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
        - image: mohamadqubaisi/hello-app:v${BUILD_NUMBER}
          name: helloapp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: helloapp
