apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-travel-blog
  name: my-travel-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-travel-blog
  template:
    metadata:
      labels:
        app: my-travel-blog
    spec:
      containers:
        - image: mohamadqubaisi/my-travel-blog:v{BUILD_NUMBER}
          name: my-travel-blog
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: my-travel-blog-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: my-travel-blog
