apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
spec:
  ports:
    - name: helloport
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: helloapp
  type: NodePort
status:
  loadBalancer: {}
